# modules/eks/templates/fluent-bit-values.yaml

serviceAccount:
  create: true
  name: fluent-bit

config:
  outputs: |
    [OUTPUT]
        Name cloudwatch
        Match *
        region ${region}
        log_group_name ${log_group_name}
        log_stream_prefix from-fluent-bit-
        auto_create_group true

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

tolerations:
  - operator: Exists

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi